name = "gmb-automation-backend"
main = "src/worker.mjs"
compatibility_date = "2025-01-01"

[vars]
POST_ATTACH_MEDIA = "true"

[[d1_databases]]
binding = "D1_DB"
database_name = "gmb_automation"
database_id = "10cb08e3-b625-430f-b1e6-a86a1c1dc253"

[triggers]
crons = ["* * * * *"]

[[r2_buckets]]
binding = "MEDIA_BUCKET"
bucket_name = "gmb-media"
